<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>NeoMapper</PackageId>
    <Version>1.0.6</Version>
    <Authors>Francis Fulgencio</Authors>
    <Company>TuEmpresa</Company>
    <Description>NeoMapper is a lightweight, generic mapper for .NET 8 and later versions that converts entities to DTOs and vice versa using extension methods and custom attributes.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/codeprofe/NeoMapper</RepositoryUrl>
    <PackageProjectUrl>https://github.com/codeprofe/NeoMapper</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>mapper mapping dto entity automapper alternative reflection</PackageTags>
    <NeutralLanguage>es</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\"/>
    <None Include="../../LICENSE" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
